# Generated by Django 2.2.3 on 2019-07-28 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation date')),
                ('story', models.CharField(default='Once upon a time...', max_length=5000)),
                ('career_path', models.CharField(max_length=50)),
                ('career_level', models.PositiveIntegerField(default=1)),
                ('total_xp', models.IntegerField(default=0)),
                ('spent_xp', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('game_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date played')),
                ('description', models.CharField(max_length=2000)),
                ('xp_for_all', models.IntegerField(default=0, verbose_name='Experience for all players')),
                ('characters', models.ManyToManyField(related_name='characters', to='history.Character')),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Player')),
            ],
        ),
    ]
