# Generated by Django 2.2.3 on 2019-07-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='desciption',
            new_name='description',
        ),
    ]
