# Generated by Django 2.2.3 on 2019-07-22 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190722_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spent_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='characters',
            field=models.ManyToManyField(related_name='characters', to='history.Character'),
        ),
        migrations.AlterField(
            model_name='session',
            name='game_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date played'),
        ),
    ]
