# Generated by Django 2.2.3 on 2019-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20190723_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.CharField(default='Once upon a time...', max_length=5000),
        ),
    ]
